<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [
            ['ten'=>'Tin học ứng dụng','mamon'=>'ACC201','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Nguyên lý kế toán','mamon'=>'ACC202','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Kế toán tài chính 1','mamon'=>'ACC301','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Kế toán tài chính 2','mamon'=>'ACC302','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Kế toán quản trị','mamon'=>'ACC304','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Thuế','mamon'=>'ACC401','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Kiểm toán căn bản','mamon'=>'ACC403','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tổ chức công tác kế toán','mamon'=>'ACC503','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Kế toán hành chính sự nghiệp','mamon'=>'ACC504','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Kiểm toán nội bộ','mamon'=>'ACC506','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Phân tích báo cáo tài chính','mamon'=>'ACC508','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Kiểm toán tài chính','mamon'=>'ACC509','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Cấu trúc dữ liệu và giải thuật','mamon'=>'CS101','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Kỹ năng soạn thảo văn bản kinh tế và QLDN','mamon'=>'DWS104','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Kinh tế vi mô','mamon'=>'ECO101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Kinh tế vĩ mô','mamon'=>'ECO102','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Anh văn thương mại','mamon'=>'EBA201','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Anh văn ngành TCKT','mamon'=>'EFI204','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tiếng Anh chuyên ngành','mamon'=>'EIT201','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tiếng anh cơ bản 1','mamon'=>'ENG101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tiếng anh cơ bản 2','mamon'=>'ENG102','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tiếng anh cơ bản 3','mamon'=>'ENG103','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Lý thuyết tài chính tiền tệ','mamon'=>'FIN101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tài chính doanh nghiệp','mamon'=>'FIN102','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Thị trường chứng khoán','mamon'=>'FIN301','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Thanh toán quốc tế','mamon'=>'FIN505','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Nhập môn Internet và E-Learning','mamon'=>'ICT101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tin học đại cương','mamon'=>'ICT102','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Thương mại điện tử','mamon'=>'ICT401','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Nhập môn hệ điều hành','mamon'=>'IT101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Cơ bản về mạng máy tính','mamon'=>'IT102','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'An ninh mạng','mamon'=>'IT201','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Kỹ thuật đồ họa','mamon'=>'IT202','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tương tác giữa người SD và ứng dụng','mamon'=>'IT204','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Kiến trúc ứng dụng trong doanh nghiệp','mamon'=>'IT205','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Hệ quản trị cơ sở dữ liệu SQL sever','mamon'=>'IT209','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Pháp luật đại cương','mamon'=>'LAW101','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Hiến pháp','mamon'=>'LAW103','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Hành chính','mamon'=>'LAW104','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Hình sự','mamon'=>'LAW105','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Dân sự I','mamon'=>'LAW106','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Thương mại I','mamon'=>'LAW108','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Lao động','mamon'=>'LAW109','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Ngân hàng','mamon'=>'LAW111','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Đất đai','mamon'=>'LAW112','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Môi trường','mamon'=>'LAW113','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Công pháp quốc tế','mamon'=>'LAW114','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tư pháp quốc tế','mamon'=>'LAW115','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật sở hữu trí tuệ','mamon'=>'LAW116','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật an sinh xã hội','mamon'=>'LAW117','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật tài chính công','mamon'=>'LAW118','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Pháp luật tài chính doanh nghiệp','mamon'=>'LAW119','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Pháp luật thị trường chứng khoán','mamon'=>'LAW120','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật cạnh tranh','mamon'=>'LAW121','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật kinh tế','mamon'=>'LAW201','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật học so sánh','mamon'=>'LAW202','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Dân sự II','mamon'=>'LAW206','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Tố tụng hình sự','mamon'=>'LAW305','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Tố tụng dân sự','mamon'=>'LAW306','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật công ty so sánh','mamon'=>'LAW401','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Đại diện thương nhân trung gian','mamon'=>'LAW402','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Mua bán sáp nhật và hợp nhất doanh nghiệp','mamon'=>'LAW405','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Logic học đại cương','mamon'=>'LAW703','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị học','mamon'=>'MAN301','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tâm lý học quản trị kinh doanh','mamon'=>'MAN303','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị marketing','mamon'=>'MAN304','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị nguồn nhân lực','mamon'=>'MAN305','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị dự án đầu tư','mamon'=>'MAN306','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Khởi tạo doanh nghiệp','mamon'=>'MAN307','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị chiến lược','mamon'=>'MAN308','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị sản xuất','mamon'=>'MAN309','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Phân tích hoạt động kinh doanh','mamon'=>'MAN310','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị bán hàng','mamon'=>'MAN401','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Hệ thống thông tin quản lý','mamon'=>'MAN402','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Hành vi tổ chức','mamon'=>'MAN403','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản trị kinh doanh','mamon'=>'MAN413','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Marketing căn bản','mamon'=>'MAR201','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Toán cao cấp 1','mamon'=>'MAT101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Toán cao cấp 2','mamon'=>'MAT102','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Toán rời rạc','mamon'=>'MAT104','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Tư tưởng Hồ Chí Minh','mamon'=>'PHH101','so_tin_chi'=>2,'ti_le_diem_thi'=>70],
            ['ten'=>'Những nguyên lý cơ bản của chủ nghĩa Mác-Lê 1 (5TC)','mamon'=>'PHM1015','so_tin_chi'=>5,'ti_le_diem_thi'=>70],
            ['ten'=>'Những nguyên lý cơ bản của chủ nghĩa Mác-Lê 1 (2TC)','mamon'=>'PHM101','so_tin_chi'=>2,'ti_le_diem_thi'=>70],
            ['ten'=>'Những nguyên lý cơ bản của chủ nghĩa Mác-Lê 2','mamon'=>'PHM102','so_tin_chi'=>3,'ti_le_diem_thi'=>70],
            ['ten'=>'Đường lối cách mạng ĐCS Việt Nam','mamon'=>'PHP101','so_tin_chi'=>3,'ti_le_diem_thi'=>70],
            ['ten'=>'Phát triển kỹ năng cá nhân 1','mamon'=>'PSD101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Phát triển kỹ năng cá nhân 2','mamon'=>'PSD102','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Nhập môn lập trình ( C)','mamon'=>'SE101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Kỹ thuật xây dựng web','mamon'=>'SE201','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Cơ sở dữ liệu','mamon'=>'SE202','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Lập trình ứng dụng cho máy tính cá nhân C#','mamon'=>'SE203','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Lập trình hướng đối tượng','mamon'=>'SE204','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Lập trình web','mamon'=>'SE205','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Phân tích và thiết kế HTTT','mamon'=>'SE206','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản lý chất lượng phần mềm','mamon'=>'SE301','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Quản lý dự án phần mềm','mamon'=>'SE302','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Lập trình mã nguồn mở PHP & MySQL','mamon'=>'SE401','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Phát triển ứng dụng web với java','mamon'=>'SE403','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Dự án mã nguồn mở','mamon'=>'SE405','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Lý thuyết xác suất và thống kê toán','mamon'=>'STA201','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Kinh tế lượng','mamon'=>'STA301','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Nguyên lý thống kê kinh tế','mamon'=>'STA302','so_tin_chi'=>2,'ti_le_diem_thi'=>60],
            ['ten'=>'Lý luận Nhà nước và pháp luật','mamon'=>'TGL101','so_tin_chi'=>3,'ti_le_diem_thi'=>60],
            ['ten'=>'Lập trình ứng dụng','mamon'=>'TH901','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Công nghệ phần mềm ứng dụng','mamon'=>'TH902','so_tin_chi'=>4,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật Hôn nhân và gia đình','mamon'=>'PLHNGĐ','so_tin_chi'=>0,'ti_le_diem_thi'=>60],
            ['ten'=>'Luật tố tụng hành chính','mamon'=>'LTTHC','so_tin_chi'=>0,'ti_le_diem_thi'=>60],
            ['ten'=>'Kế toán máy','mamon'=>'ACC602','so_tin_chi'=>0,'ti_le_diem_thi'=>60],
            ['ten'=>'Kế toán thuế','mamon'=>'ACC601','so_tin_chi'=>0,'ti_le_diem_thi'=>60],
            ['ten'=>'Đạo đức kinh doanh và văn hóa doanh nghiệp','mamon'=>'MAN602','so_tin_chi'=>0,'ti_le_diem_thi'=>60],
        ];
        DB::table('mons')->insert($list);
    }
}
